/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class formularioConsultaYModificacionDoctores extends javax.swing.JFrame {

    /**
     * Creates new form formularioConsultaYModificacionDoctores
     */
    public formularioConsultaYModificacionDoctores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaCorreoElectronico = new javax.swing.JLabel();
        botonDeGuardar = new javax.swing.JButton();
        etiquetaEstadoCivil = new javax.swing.JLabel();
        etiquetaID = new javax.swing.JLabel();
        etiquetaIDHospital = new javax.swing.JLabel();
        textoIDdeBusqueda = new javax.swing.JTextField();
        textoEstadoCivil = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        textoApellidos = new javax.swing.JTextField();
        textoCedula = new javax.swing.JTextField();
        etiquetaTitulo = new javax.swing.JLabel();
        textoCorreoElectronico = new javax.swing.JTextField();
        etiquetaCedulaID = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        textoIDHospital = new javax.swing.JTextField();
        etiquetaApellidos = new javax.swing.JLabel();
        botonDeRegreso = new javax.swing.JButton();
        etiquetaGradoAcademico = new javax.swing.JLabel();
        textoGradoAcademico = new javax.swing.JTextField();
        etiquetaEspecialidad = new javax.swing.JLabel();
        textoEspecialidad = new javax.swing.JTextField();
        estatus = new javax.swing.JCheckBox();
        imagenFondo = new javax.swing.JLabel();
        textoIDHospital1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCorreoElectronico.setText("Correo Electronico");
        getContentPane().add(etiquetaCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        botonDeGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonDeGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        botonDeGuardar.setText("Guardar");
        botonDeGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonDeGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        etiquetaEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEstadoCivil.setText("Estado Civil");
        getContentPane().add(etiquetaEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        etiquetaID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaID.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaID.setText("Digite el ID del doctor que desea buscar");
        getContentPane().add(etiquetaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        etiquetaIDHospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaIDHospital.setText("ID Hospital");
        getContentPane().add(etiquetaIDHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        textoIDdeBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(textoIDdeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 130, -1));
        getContentPane().add(textoEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 150, -1));

        botonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));
        getContentPane().add(textoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 150, -1));
        getContentPane().add(textoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, -1));

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trabajadores.png"))); // NOI18N
        etiquetaTitulo.setText("Modificar y Cosultar Doctores");
        getContentPane().add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 610, 70));
        getContentPane().add(textoCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 150, -1));

        etiquetaCedulaID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCedulaID.setText("Cedula(ID)");
        getContentPane().add(etiquetaCedulaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));
        getContentPane().add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 150, -1));

        etiquetaNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaNombre.setText("Nombre");
        getContentPane().add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));
        getContentPane().add(textoIDHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 150, -1));

        etiquetaApellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaApellidos.setText("Apellidos");
        getContentPane().add(etiquetaApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        botonDeRegreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonDeRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salir.gif"))); // NOI18N
        botonDeRegreso.setText("Regresar");
        botonDeRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeRegresoActionPerformed(evt);
            }
        });
        getContentPane().add(botonDeRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        etiquetaGradoAcademico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaGradoAcademico.setText("Grado Academico");
        getContentPane().add(etiquetaGradoAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        textoGradoAcademico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textoGradoAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 150, 30));

        etiquetaEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEspecialidad.setText("Especialidad");
        getContentPane().add(etiquetaEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));
        getContentPane().add(textoEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 330, 150, 30));

        estatus.setText("Activo");
        getContentPane().add(estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes de Fondo/fondo inicio.jpg"))); // NOI18N
        getContentPane().add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 430));
        getContentPane().add(textoIDHospital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDeGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeGuardarActionPerformed
        // Se guardan los datos almacenados:

        JOptionPane.showMessageDialog(null, "El doctor se modifico con exito");
    }//GEN-LAST:event_botonDeGuardarActionPerformed

    private void botonDeRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeRegresoActionPerformed
        // boton para regresar a la pantalla de pacientes:
        setVisible(false);
        new doctores().setVisible(true);
    }//GEN-LAST:event_botonDeRegresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioConsultaYModificacionDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioConsultaYModificacionDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioConsultaYModificacionDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioConsultaYModificacionDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new formularioConsultaYModificacionDoctores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonDeGuardar;
    private javax.swing.JButton botonDeRegreso;
    private javax.swing.JCheckBox estatus;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaCedulaID;
    private javax.swing.JLabel etiquetaCorreoElectronico;
    private javax.swing.JLabel etiquetaEspecialidad;
    private javax.swing.JLabel etiquetaEstadoCivil;
    private javax.swing.JLabel etiquetaGradoAcademico;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaIDHospital;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoCedula;
    private javax.swing.JTextField textoCorreoElectronico;
    private javax.swing.JTextField textoEspecialidad;
    private javax.swing.JTextField textoEstadoCivil;
    private javax.swing.JTextField textoGradoAcademico;
    private javax.swing.JTextField textoIDHospital;
    private javax.swing.JTextField textoIDHospital1;
    private javax.swing.JTextField textoIDdeBusqueda;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
