/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class formularioAgregarDoctores extends javax.swing.JFrame {

    /**
     * Creates new form formularioAgregarDoctores
     */
    public formularioAgregarDoctores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaID = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etiquetaApellidos = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        etiquetaCorreo = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JTextField();
        etiquetaEstadoCivil = new javax.swing.JLabel();
        textoEstadoCivil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textoIDHospital = new javax.swing.JTextField();
        etiquetaGradoAcademico = new javax.swing.JLabel();
        textoGradoAcademico = new javax.swing.JTextField();
        etiquetaEspecialidad = new javax.swing.JLabel();
        textoEspacialidad = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setText("Agregar Doctores");
        getContentPane().add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 25, -1, -1));

        etiquetaID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaID.setText("Cedula(ID)");
        getContentPane().add(etiquetaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 122, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 155, 150, -1));

        etiquetaNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaNombre.setText("Nombre");
        getContentPane().add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 122, -1, -1));
        getContentPane().add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 155, 150, -1));

        etiquetaApellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaApellidos.setText("Apellidos");
        getContentPane().add(etiquetaApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 122, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 155, 150, -1));

        etiquetaCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCorreo.setText("Correo Electronico");
        getContentPane().add(etiquetaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 122, -1, -1));
        getContentPane().add(textoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 155, 150, -1));

        etiquetaEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEstadoCivil.setText("Estdo Civil");
        getContentPane().add(etiquetaEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 268, -1, -1));
        getContentPane().add(textoEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 306, 150, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Hospital");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 268, -1, -1));
        getContentPane().add(textoIDHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 306, 150, -1));

        etiquetaGradoAcademico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaGradoAcademico.setText("Grado Academico");
        getContentPane().add(etiquetaGradoAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 268, -1, -1));
        getContentPane().add(textoGradoAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 306, 153, -1));

        etiquetaEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEspecialidad.setText("Especialidad");
        getContentPane().add(etiquetaEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 100, -1));
        getContentPane().add(textoEspacialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 306, 150, -1));

        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 377, -1, -1));

        botonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salir.gif"))); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 377, -1, -1));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes de Fondo/fondo inicio.jpg"))); // NOI18N
        getContentPane().add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // boton para guardar al usuario:
        
       JOptionPane.showMessageDialog(null, "El doctor se ingreso con exito");
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // boton para regresar al menu de doctores:
        
        setVisible(false);
        new doctores().setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioAgregarDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioAgregarDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioAgregarDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioAgregarDoctores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioAgregarDoctores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaEspecialidad;
    private javax.swing.JLabel etiquetaEstadoCivil;
    private javax.swing.JLabel etiquetaGradoAcademico;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoEspacialidad;
    private javax.swing.JTextField textoEstadoCivil;
    private javax.swing.JTextField textoGradoAcademico;
    private javax.swing.JTextField textoIDHospital;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
