/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author franc
 */
public class hospitales extends javax.swing.JFrame {

    /**
     * Creates new form hospitales
     */
    public hospitales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        BotonAgregarHospital = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonListaHospitales = new javax.swing.JButton();
        BotonListaDoctores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarHospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonAgregarHospital.setText("Agregar Hospital");
        BotonAgregarHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        BotonModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 130, -1));

        BotonListaHospitales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonListaHospitales.setText("Lista de Hospitales");
        BotonListaHospitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaHospitalesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonListaHospitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        BotonListaDoctores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonListaDoctores.setText("Lista de Doctores");
        BotonListaDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaDoctoresActionPerformed(evt);
            }
        });
        getContentPane().add(BotonListaDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salir.gif"))); // NOI18N
        jButton1.setText("Regresar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 312, -1, -1));

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Menu Hospitales");
        getContentPane().add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 44, 154, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes de Fondo/fondo inicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarHospitalActionPerformed
        // ir a la pantalla para agregar hospitales:
        setVisible(false);
        new formularioAgregarHospital().setVisible(true);
    }//GEN-LAST:event_BotonAgregarHospitalActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // ir a la pantalla para agregar hospitales:
        setVisible(false);
        new formularioModificarHospital().setVisible(true);
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void BotonListaHospitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaHospitalesActionPerformed
        // Ir a la lista de hospitales:
        setVisible(false);
        new listaHospitales().setVisible(true);
    }//GEN-LAST:event_BotonListaHospitalesActionPerformed

    private void BotonListaDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaDoctoresActionPerformed
        // Ir a la lista de doctores:
        setVisible(false);
        new listaDoctores().setVisible(true);
    }//GEN-LAST:event_BotonListaDoctoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new hospitales().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarHospital;
    private javax.swing.JButton BotonListaDoctores;
    private javax.swing.JButton BotonListaHospitales;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
